//
// Generated file, do not edit! Created by nedtool 5.6 from serverAppendEntriesMsg.msg.
//

#ifndef __SERVERAPPENDENTRIESMSG_M_H
#define __SERVERAPPENDENTRIESMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "logEntry.h"
typedef std::list<_logEntry> logList;
// }}

/**
 * Class generated from <tt>serverAppendEntriesMsg.msg:26</tt> by nedtool.
 * <pre>
 * message ServerAppendEntriesMsg
 * {
 *     int term;			// leader’s term
 *     int leaderId;		// so follower can redirect clients
 *     int prevLogIndex; 	// index of log entry immediately preceding new ones
 *     int prevLogTerm; 	// term of prevLogIndex entry
 *     logList entries;  // log entries to store (empty for heartbeat; may send more than one for efficiency)
 *     int leaderCommit;	// Leader’s commitIndex
 * }
 * </pre>
 */
class ServerAppendEntriesMsg : public ::omnetpp::cMessage
{
  protected:
    int term;
    int leaderId;
    int prevLogIndex;
    int prevLogTerm;
    logList entries;
    int leaderCommit;

  private:
    void copy(const ServerAppendEntriesMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ServerAppendEntriesMsg&);

  public:
    ServerAppendEntriesMsg(const char *name=nullptr, short kind=0);
    ServerAppendEntriesMsg(const ServerAppendEntriesMsg& other);
    virtual ~ServerAppendEntriesMsg();
    ServerAppendEntriesMsg& operator=(const ServerAppendEntriesMsg& other);
    virtual ServerAppendEntriesMsg *dup() const override {return new ServerAppendEntriesMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getTerm() const;
    virtual void setTerm(int term);
    virtual int getLeaderId() const;
    virtual void setLeaderId(int leaderId);
    virtual int getPrevLogIndex() const;
    virtual void setPrevLogIndex(int prevLogIndex);
    virtual int getPrevLogTerm() const;
    virtual void setPrevLogTerm(int prevLogTerm);
    virtual logList& getEntries();
    virtual const logList& getEntries() const {return const_cast<ServerAppendEntriesMsg*>(this)->getEntries();}
    virtual void setEntries(const logList& entries);
    virtual int getLeaderCommit() const;
    virtual void setLeaderCommit(int leaderCommit);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ServerAppendEntriesMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ServerAppendEntriesMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SERVERAPPENDENTRIESMSG_M_H

